name: CI, Test & Release

on:
  push:
    branches: ["**"]
    tags: ["v*.*.*"]
  pull_request:
    branches: ["**"]

env:
  PROJECT: rat

jobs:
  build:
    name: Build & Test on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        target:
          - x86_64-unknown-linux-gnu
          - x86_64-apple-darwin
          - x86_64-pc-windows-msvc

    steps:
      - uses: actions/checkout@v3

      - uses: actions/cache@v4
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
            target
          key: ${{ matrix.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}

      - run: rustup target add ${{ matrix.target }}

      - run: cargo test --target ${{ matrix.target }} --locked --verbose

      - run: cargo build --release --target ${{ matrix.target }}

      - run: |
          EXT=""
          [ "${{ matrix.os }}" = windows-latest ] && EXT=".exe"
          SRC="target/${{ matrix.target }}/release/${{ env.PROJECT }}${EXT}"
          DST="${{ env.PROJECT }}-${{ matrix.target }}${EXT}"
          cp "$SRC" "$DST"
          echo "Packaged: $DST"

      - uses: actions/upload-artifact@v4
        with:
          name: build-${{ matrix.target }}
          path: "${{ env.PROJECT }}-${{ matrix.target }}*"

  release:
    name: Create Release (on tag)
    runs-on: ubuntu-latest
    needs: build
    if: startsWith(github.ref, 'refs/tags/v')
    env:
      PROJECT: rat

    steps:
      - uses: actions/checkout@v3

      - uses: actions/download-artifact@v4
        with:
          path: ./artifacts
          merge-multiple: true

      - run: |
          cd artifacts
          for file in *; do
            sha256sum "$file" > "$file".sha256
          done

      - uses: houseabsolute/actions-rust-release@v0
        with:
          executable-name: ${{ env.PROJECT }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          tag: ${{ github.ref }}
          file: artifacts/*.sha256
